---
services:
  zookeeper:
    image: docker.io/zookeeper:3.5.9
    hostname: zookeeper
    restart: on-failure
    healthcheck:
      test: zkCli.sh get / || exit 1
      interval: 1s
      retries: 15
    volumes:
      - type: volume
        source: zookeeper_data
        target: /data
      - type: volume
        source: zookeeper_datalog
        target: /datalog
      - type: volume
        source: zookeeper_logs
        target: /logs
  zookeeper_init:
    depends_on:
      - zookeeper
    image: ${ZOOKEEPER_IMAGE:-docker.io/zookeeper}:${ZOOKEEPER_VERSION:-3.5.9}
    restart: on-failure
    command:
      - bash
      - -c
      - > 
        zkCli.sh -server zookeeper:2181 get /clickhouse
        || zkCli.sh -server zookeeper:2181 create /clickhouse
    volumes:
      - type: tmpfs
        target: /data
      - type: tmpfs
        target: /datalog
      - type: tmpfs
        target: /logs
  clickhouse:
    depends_on:
      - zookeeper_init
    image: docker.io/library/clickhouse:25.4
    hostname: clickhouse
    user: root
    environment:
      CLICKHOUSE_PASSWORD: "default"
      CLICKHOUSE_UID: 0
    healthcheck:
      test: wget -O /dev/null --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 1s
      retries: 15
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - type: volume
        source: clickhouse_data
        target: /var/lib/clickhouse
      - type: bind
        source: ./users.d
        target: /etc/clickhouse-server/users.d
      - type: bind
        source: ./config.d
        target: /etc/clickhouse-server/config.d
      - type: bind
        source: ./macros/clickhouse.xml
        target: /etc/clickhouse-server/config.d/macros.xml
      - type: bind
        source: ./user_scripts
        target: /var/lib/clickhouse/user_scripts
      - type: bind
        source: ./eudf
        target: /etc/clickhouse-server/eudf
      - type: bind
        source: ./user_files
        target: /var/lib/clickhouse/user_files
      - type: bind
        source: /opt/works
        target: /opt/works
  clickhouse_2:
    depends_on:
      - zookeeper_init
    image: docker.io/library/clickhouse:25.4
    hostname: clickhouse-2
    user: root
    environment:
      CLICKHOUSE_PASSWORD: "default"
      CLICKHOUSE_UID: 0
    healthcheck:
      test: wget -O /dev/null --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 1s
      retries: 15
    ports:
      - "8124:8123"
    volumes:
      - type: volume
        source: clickhouse_2_data
        target: /var/lib/clickhouse
      - type: bind
        source: ./users.d
        target: /etc/clickhouse-server/users.d
      - type: bind
        source: ./config.d
        target: /etc/clickhouse-server/config.d
      - type: bind
        source: ./macros/clickhouse-2.xml
        target: /etc/clickhouse-server/config.d/macros.xml
      - type: bind
        source: ./user_scripts
        target: /var/lib/clickhouse/user_scripts
      - type: bind
        source: ./eudf
        target: /etc/clickhouse-server/eudf
      - type: bind
        source: ./user_files
        target: /var/lib/clickhouse/user_files
      - type: bind
        source: /opt/works
        target: /opt/works
  clickhouse_3:
    depends_on:
      - zookeeper_init
    image: docker.io/library/clickhouse:25.4
    hostname: clickhouse-3
    user: root
    environment:
      CLICKHOUSE_PASSWORD: "default"
      CLICKHOUSE_UID: 0
    healthcheck:
      test: wget -O /dev/null --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 1s
      retries: 15
    ports:
      - "8125:8123"
    volumes:
      - type: volume
        source: clickhouse_3_data
        target: /var/lib/clickhouse
      - type: bind
        source: ./users.d
        target: /etc/clickhouse-server/users.d
      - type: bind
        source: ./config.d
        target: /etc/clickhouse-server/config.d
      - type: bind
        source: ./macros/clickhouse-3.xml
        target: /etc/clickhouse-server/config.d/macros.xml
      - type: bind
        source: ./user_scripts
        target: /var/lib/clickhouse/user_scripts
      - type: bind
        source: ./eudf
        target: /etc/clickhouse-server/eudf
      - type: bind
        source: ./user_files
        target: /var/lib/clickhouse/user_files
      - type: bind
        source: /opt/works
        target: /opt/works

volumes:
  zookeeper_data:
  zookeeper_datalog:
  zookeeper_logs:
  clickhouse_data:
  clickhouse_2_data:
  clickhouse_3_data:
