---
services:
  clickhouse:
    image: docker.io/library/clickhouse:25.4
    hostname: clickhouse
    user: root
    environment:
      CLICKHOUSE_PASSWORD: "default"
      CLICKHOUSE_UID: 0
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: wget -O /dev/null --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 1s
      retries: 15
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - type: volume
        source: clickhouse_data
        target: /var/lib/clickhouse
      - type: bind
        source: ./users.d
        target: /etc/clickhouse-server/users.d
      - type: bind
        source: ./config.d
        target: /etc/clickhouse-server/config.d
      - type: bind
        source: ./user_scripts
        target: /var/lib/clickhouse/user_scripts
      - type: bind
        source: ./eudf
        target: /etc/clickhouse-server/eudf
      - type: bind
        source: ./user_files
        target: /var/lib/clickhouse/user_files
      - type: bind
        source: ./clickhouse-backup
        target: /etc/clickhouse-backup
      - type: bind
        source: /opt/works
        target: /opt/works
  minio:
    image: docker.io/bitnami/minio:2024.4.18
    hostname: minio
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "miniosecret"
      MINIO_DISTRIBUTED_MODE_ENABLED: "no"
      MINIO_SKIP_CLIENT: "yes"
    restart: always
    ports:
      - "59000:9000"
      - "59001:9001"
    volumes:
      - type: volume
        source: minio_data
        target: /bitnami/minio/data


volumes:
  clickhouse_data:
  minio_data:
